behaviors:
  Peanguin:
    trainer_type: ppo
    hyperparameters:
      buffer_size: 2048
      beta: 0.001
    network_settings:
      hidden_units: 256
    max_steps: 1000000
    time_horizon: 128
    summary_freq: 5000
